# Generated by Django 3.2.5 on 2021-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
