# Generated by Django 3.2.5 on 2021-08-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
