# Generated by Django 3.2.5 on 2021-08-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
    ]
