# Generated by Django 3.2.5 on 2021-08-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210802_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
