# Generated by Django 3.2.5 on 2021-09-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
