# Generated by Django 3.2.5 on 2021-09-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_sale_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
    ]
