# Generated by Django 3.2.5 on 2021-09-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_paymente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='paymente',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paymente',
        ),
    ]
